In [2]:
#creation of list
list1 = ['ele1','ele2','ele3','ele4']
list2 = ['ele5','ele6','ele1','ele2']
#concatenation of lists
list3 = list1 + list2
list3

['ele1', 'ele2', 'ele3', 'ele4', 'ele5', 'ele6', 'ele1', 'ele2']

In [8]:
#removing duplicates 
#list is converted to set
set(list3)

#append operation in list
list3.append('appended_element')
list3


['ele1',
 'ele2',
 'ele3',
 'ele4',
 'ele5',
 'ele6',
 'ele1',
 'ele2',
 'appended_element',
 'appended_element']

In [9]:
#Remove operation in list 
list3.remove('appended_element')
list3

['ele1',
 'ele2',
 'ele3',
 'ele4',
 'ele5',
 'ele6',
 'ele1',
 'ele2',
 'appended_element']

In [10]:
#Pop operation in list
list3.pop()

'appended_element'

In [11]:
list3

['ele1', 'ele2', 'ele3', 'ele4', 'ele5', 'ele6', 'ele1', 'ele2']

In [13]:
#Reverse operation list
list3.reverse()
list3
#sort list
list3.sort()
#copying list 
list4=list3.copy()
list4


['ele1', 'ele1', 'ele2', 'ele2', 'ele3', 'ele4', 'ele5', 'ele6']

In [18]:
# for deleting elements in list
list3.clear()
list3

[]

In [15]:
#counting occurance of perticuler element
list3.count('éle1')
list3.count('ele4')

1

In [19]:
#tuple operations
#Declaration of tuple
tuple1 = ('tup_ele1','tup_ele2','tup_ele3','tup_ele3')
tuple1

('tup_ele1', 'tup_ele2', 'tup_ele3', 'tup_ele3')

In [23]:
#Counting occurance of element
tuple1.count('tup_ele1')
#Fetching index of element
tuple1.index('tup_ele2')

1

In [24]:
#Dictionary declartion
dict1 = {
  "key1": "value1",
  "key2": "value2",
  "key3": "value3"
}
print(type(dict1))

<class 'dict'>


In [25]:
#Displaying all keys
dict1.keys()

dict_keys(['key1', 'key2', 'key3'])

In [26]:
#Displaying values 
dict1.values()


dict_values(['value1', 'value2', 'value3'])

In [31]:
#updating value in dictionary
dict1['key1'] = 'value4'
dict1.update({"key1": 'value1'})
dict1

{'key1': 'value1', 'key2': 'value2', 'key3': 'value3'}

In [32]:
#Inserting dictionary
dict1['key4'] = 'value4'
dict1

{'key1': 'value1', 'key2': 'value2', 'key3': 'value3', 'key4': 'value4'}

In [41]:
#Deleting last element of dictionary
print(dict1.pop("key4"))
dict1


value4


{'key1': 'value1', 'key2': 'value2', 'key3': 'value3'}

In [42]:
print(dict1.popitem())
dict1

('key3', 'value3')


{'key1': 'value1', 'key2': 'value2'}

In [43]:
#copying dictionary
dict2 = dict1.copy()
dict2

{'key1': 'value1', 'key2': 'value2'}

In [44]:
#numpy functionalities
import numpy as np
#Checking numpy version
print(np.__version__)

1.19.4


In [57]:
#one dimension array declaration
one_dim = np.array([1, 2, 3, 4, 5])
#Printing array
print(one_dim)
#Finding dimension of array
one_dim.ndim
#Accessing array element
one_dim[4]
#Two dimension array declaration
two_dim = np.array([[1,2,3],[4,5,6]])
#Printing array
two_dim
#Finding dimension of array
two_dim.ndim
#Accessing array element
two_dim[0,2]


[1 2 3 4 5]


5

In [55]:
#Three dimension array declaration
three_dim = np.array([[ [1,2,3],[4,5,6] ],[ [7,8,9],[10,11,12] ] ])
#Printing array
three_dim
#Finding dimension of array
three_dim.ndim
#Accessing array element
three_dim[1,1,1]

11

In [64]:
#slicing array
one_dim[0:3]    #Index 3 is not included [start,end]
one_dim[0:-1]   #Use of negative index  
one_dim[0:4:2]  #Step of size=2 [start,end,step]
one_dim[2:]     #starts with index 2
one_dim[:2]     #ends with index=1

array([1, 2])

(5,)

In [72]:
one_dim = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
one_dim
#shape of array
one_dim.shape


(12,)

In [75]:
#Reshaping of array
new_one_dim=one_dim.reshape(2,6)
new_one_dim.shape
new_one_dim_2=one_dim.reshape(2,2,3)
new_one_dim_2.shape

(2, 2, 3)

In [80]:
#joining array
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)
two_dim_arr1 = np.array([[1,2],[3,4]])
two_dim_arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((two_dim_arr1, two_dim_arr2), axis=1)
print(arr)

[1 2 3 4 5 6]
[[1 2 5 6]
 [3 4 7 8]]


In [85]:
import pandas as pd
arr3 = [1, 7, 2]
#Create a Series
pd1 = pd.Series(arr3)
print(pd1)
#Creation of index
index1 = ["index1", "index2","index3"]
pd2 = pd.Series(arr3,index= index1)

0    1
1    7
2    2
dtype: int64


In [95]:
import pandas as pd
dict_content = {
  "List1_index": [0, 1 , 2 ],
  "List2_index": [3 , 4, 5]
}
#Dictionary to dataframe
pd3=pd.DataFrame(dict_content)
#Printing Dataframe
pd3
#accesing data in column
pd3["List2_index"]

0    3
1    4
2    5
Name: List2_index, dtype: int64

In [99]:
import pandas as pd
#reading file 
df = pd.read_csv('/content/sample_data/mnist_test.csv') #pd.read_csv(path_of_file)
print(df) 
df.head()
df.tail()
df.info()

      7  0  0.1  0.2  0.3  0.4  ...  0.662  0.663  0.664  0.665  0.666  0.667
0     2  0    0    0    0    0  ...      0      0      0      0      0      0
1     1  0    0    0    0    0  ...      0      0      0      0      0      0
2     0  0    0    0    0    0  ...      0      0      0      0      0      0
3     4  0    0    0    0    0  ...      0      0      0      0      0      0
4     1  0    0    0    0    0  ...      0      0      0      0      0      0
...  .. ..  ...  ...  ...  ...  ...    ...    ...    ...    ...    ...    ...
9994  2  0    0    0    0    0  ...      0      0      0      0      0      0
9995  3  0    0    0    0    0  ...      0      0      0      0      0      0
9996  4  0    0    0    0    0  ...      0      0      0      0      0      0
9997  5  0    0    0    0    0  ...      0      0      0      0      0      0
9998  6  0    0    0    0    0  ...      0      0      0      0      0      0

[9999 rows x 785 columns]
<class 'pandas.core.frame.DataFrame'>